version: "3.8"

networks:
  web-net:
    driver: bridge

services:
  db:
    image: postgres:14-alpine3.17
    container_name: db

    env_file:
      - db_main.env
    networks:
      - web-net

  dbtest:
    image: postgres:14-alpine3.17
    container_name: dbtest
    env_file:
      - db_test.env
    networks:
      - web-net
    depends_on:
      - db

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - '6379:6379'
    networks:
      - web-net

  site:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: site
    env_file:
      - .env
    depends_on:
      - db
      - dbtest
      - redis
    networks:
      - web-net

  nginx:
    container_name: nginx
    build: nginx
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - site
    restart: always
    networks:
      - web-net

