"""v5 email field not null

Revision ID: 238585c68dbc
Revises: f5bd01963014
Create Date: 2023-02-27 11:16:12.392551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '238585c68dbc'
down_revision = 'f5bd01963014'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###
